// Assembly System.Data.SqlXml, Version 2.0.0.0

[assembly: System.Reflection.AssemblyDescription("System.Data.SqlXml.dll")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Data.SqlXml.dll")]
[assembly: System.Reflection.AssemblyTitle("System.Data.SqlXml.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Runtime.CompilerServices.Dependency("System.Xml,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\EcmaPublicKey.snk")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.50727.5494")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Resources.SatelliteContractVersion("2.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("System.Xml, PublicKey=00000000000000000400000000000000")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.5494")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

