namespace MigraDoc.DocumentObjectModel
{
    using System;

    internal enum DomMsgID
    {
        BaseStyleRequired = 1,
        BoolExpected = 0x3f2,
        EmptyBaseStyle = 2,
        EndOfFileExpected = 0x3ed,
        EscapeSequenceNotAllowed = 0x40d,
        IdentifierExpected = 0x3f1,
        InsertNullNotAllowed = 12,
        IntegerExpected = 0x3f4,
        InvalidAssignment = 0x3fa,
        InvalidColor = 0x3fd,
        InvalidColorString = 10,
        InvalidDocumentObjectType = 15,
        InvalidEnum = 0x3f8,
        InvalidEnumForLeftPosition = 8,
        InvalidEnumForTopPosition = 9,
        InvalidFieldFormat = 3,
        InvalidFieldType = 0x3fe,
        InvalidFontSize = 11,
        InvalidInfoFieldName = 4,
        InvalidRange = 0x3fc,
        InvalidSymbolType = 0x400,
        InvalidType = 0x3f9,
        InvalidUnitType = 7,
        InvalidUnitValue = 6,
        InvalidValueForOperation = 0x3ff,
        InvalidValueName = 0x3fb,
        KeyWordExpected = 0x3ec,
        MissingBraceLeft = 0x401,
        MissingBraceRight = 0x402,
        MissingBracketLeft = 0x403,
        MissingBracketRight = 0x404,
        MissingComma = 0x407,
        MissingObligatoryProperty = 14,
        MissingParenLeft = 0x405,
        MissingParenRight = 0x406,
        NewlineInString = 0x40c,
        NoAccess = 0x40b,
        NullAssignmentNotSupported = 0x40e,
        NullExpected = 0x3f6,
        NumberExpected = 0x3f7,
        OperatorExpected = 0x3eb,
        OutOfRange = 0x40f,
        ParentAlreadySet = 13,
        RealExpected = 0x3f3,
        StringExpected = 0x3f5,
        StyleExpected = 0,
        StyleNameExpected = 0x3ef,
        Success = 0x3e8,
        SymbolExpected = 0x3e9,
        SymbolIsNotAnObject = 0x409,
        SymbolNotAllowed = 0x408,
        SymbolsExpected = 0x3ea,
        UndefinedBaseStyle = 5,
        UnexpectedEndOfFile = 0x3ee,
        UnexpectedSymbol = 0x3f0,
        UnknownChartType = 0x40a,
        UseOfUndefinedBaseStyle = 0x410,
        UseOfUndefinedStyle = 0x411
    }
}

