// Assembly System.Transactions, Version 2.0.0.0

[assembly: System.Runtime.InteropServices.ComCompatibleVersion(1, 0, 0xce4, 0)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\EcmaPublicKey.snk")]
[assembly: System.Runtime.InteropServices.BestFitMapping(false)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyTitle("System.Transactions.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Transactions.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Transactions.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.5483")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.50727.5483")]
[assembly: System.Resources.SatelliteContractVersion("2.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum)]

