// Assembly System.Web.Abstractions, Version 3.5.0.0

[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyTitle("System.Web.Abstractions.dll")]
[assembly: System.Reflection.AssemblyDescription("System.Web.Abstractions.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.Web.Abstractions.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("3.5.30729.5420")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.5.30729.5420")]
[assembly: System.Resources.SatelliteContractVersion("3.5.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\35MSSharedLib1024.snk")]
[assembly: System.Runtime.CompilerServices.Dependency("System.Web,", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Execution=true)]

