namespace System.Data.Design
{
    using System;
    using System.ComponentModel;
    using System.Data;

    [DataSourceXmlClass("Parameter")]
    internal class DesignParameter : DataSourceComponent, IDbDataParameter, IDataParameter, IDataSourceNamedObject, INamedObject, ICloneable
    {
        private static int[] adoDataType2DbType = new int[] { 
            8, 0, 20, 12, 0x80, 1, 11, 3, 0x81, 0, 6, 4, 7, 5, 0x85, 5,
            0x86, 6, 0x87, 6, 14, 7, 5, 8, 0, 13, 10, 13, 0x40, 6, 0x48, 9,
            9, 13, 13, 13, 3, 11, 0xcd, 1, 0xc9, 0, 0xcb, 0x10, 0x83, 7, 0x8a, 13,
            4, 15, 2, 10, 0x10, 14, 0x15, 20, 0x13, 0x13, 0x12, 0x12, 0x11, 2, 0xcc, 1,
            200, 0, 0x8b, 0x15, 0xca, 0x10, 12, 13, 130, 0x10
        };
        private bool allowDbNull;
        private string autogeneratedName;
        private string columnName;
        private string dataSourceName;
        private string dataTypeServer;
        private System.Data.DbType dbType;
        public const string DEFAULT_RETVAL_NAME = "RETURN_VALUE";
        private ParameterDirection direction;
        private string parameterName;
        private byte precision;
        private string providerType;
        private byte scale;
        private int size;
        private string sourceColumn;
        private bool sourceColumnNullMapping;
        private DataRowVersion sourceVersion;

        public DesignParameter() : this(string.Empty)
        {
        }

        public DesignParameter(string name)
        {
            this.parameterName = name;
            this.autogeneratedName = string.Empty;
            this.direction = ParameterDirection.Input;
            this.sourceVersion = DataRowVersion.Current;
            this.dataSourceName = string.Empty;
        }

        public object Clone() => 
            new DesignParameter(this.ParameterName) { 
                ColumnName = this.ColumnName,
                AutogeneratedName = this.AutogeneratedName,
                DbType = this.DbType,
                Precision = this.Precision,
                Scale = this.Scale,
                Size = this.Size,
                DataTypeServer = this.DataTypeServer,
                Direction = this.Direction,
                SourceColumn = this.SourceColumn,
                SourceVersion = this.SourceVersion,
                SourceColumnNullMapping = this.SourceColumnNullMapping
            };

        public override bool Equals(object o)
        {
            DesignParameter parameter = o as DesignParameter;
            return parameter?.ParameterName.Equals(this.ParameterName);
        }

        public static DesignParameter GetDefaultRetvalParam()
        {
            DesignParameter parameter = new DesignParameter("RETURN_VALUE") {
                DbType = System.Data.DbType.Int32
            };
            parameter.Precision = (byte) (parameter.Scale = 0);
            parameter.Size = 4;
            parameter.Direction = ParameterDirection.ReturnValue;
            return parameter;
        }

        public override int GetHashCode() => 
            this.ParameterName.GetHashCode();

        public override string ToString() => 
            this.ParameterName;

        [DefaultValue(false), DataSourceXmlAttribute]
        public bool AllowDbNull
        {
            get => 
                this.allowDbNull;
            set
            {
                this.allowDbNull = value;
            }
        }

        [DataSourceXmlAttribute, Browsable(false)]
        public string AutogeneratedName
        {
            get => 
                this.autogeneratedName;
            set
            {
                this.autogeneratedName = value;
            }
        }

        [DataSourceXmlAttribute]
        public string ColumnName
        {
            get => 
                this.columnName;
            set
            {
                this.columnName = value;
            }
        }

        [DataSourceXmlAttribute, Browsable(false)]
        public string DataSourceName
        {
            get => 
                this.dataSourceName;
            set
            {
                this.dataSourceName = value;
            }
        }

        [DataSourceXmlAttribute, Browsable(false)]
        public string DataTypeServer
        {
            get => 
                this.dataTypeServer;
            set
            {
                this.dataTypeServer = value;
            }
        }

        [DataSourceXmlAttribute]
        public System.Data.DbType DbType
        {
            get => 
                this.dbType;
            set
            {
                this.dbType = value;
            }
        }

        [DefaultValue(1), DataSourceXmlAttribute]
        public ParameterDirection Direction
        {
            get => 
                this.direction;
            set
            {
                this.direction = value;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Never), DefaultValue(false), DesignOnly(true), Browsable(false)]
        public bool IsNullable =>
            true;

        [Browsable(false)]
        public string Name =>
            this.ParameterName;

        [DataSourceXmlAttribute, MergableProperty(false), DefaultValue("")]
        public string ParameterName
        {
            get => 
                this.parameterName;
            set
            {
                if (!StringUtil.EqualValue(this.ParameterName, value))
                {
                    if (this.CollectionParent != null)
                    {
                        this.CollectionParent.ValidateUniqueName(this, value);
                    }
                    this.parameterName = value;
                }
            }
        }

        [DataSourceXmlAttribute, DefaultValue((byte) 0)]
        public byte Precision
        {
            get => 
                this.precision;
            set
            {
                this.precision = value;
            }
        }

        [DataSourceXmlAttribute]
        public string ProviderType
        {
            get => 
                this.providerType;
            set
            {
                this.providerType = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue((byte) 0)]
        public byte Scale
        {
            get => 
                this.scale;
            set
            {
                this.scale = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue(0)]
        public int Size
        {
            get => 
                this.size;
            set
            {
                this.size = value;
                if (this.size < 0)
                {
                    this.size = 0x7fffffff;
                }
            }
        }

        [DataSourceXmlAttribute, DefaultValue("")]
        public string SourceColumn
        {
            get => 
                this.sourceColumn;
            set
            {
                this.sourceColumn = value;
            }
        }

        [DefaultValue(false), DataSourceXmlAttribute]
        public bool SourceColumnNullMapping
        {
            get => 
                this.sourceColumnNullMapping;
            set
            {
                this.sourceColumnNullMapping = value;
            }
        }

        [DataSourceXmlAttribute, DefaultValue(0x200)]
        public DataRowVersion SourceVersion
        {
            get => 
                this.sourceVersion;
            set
            {
                this.sourceVersion = value;
            }
        }

        string IDataSourceNamedObject.PublicTypeName =>
            "Parameter";

        string INamedObject.Name
        {
            get => 
                this.ParameterName;
            set
            {
                this.ParameterName = value;
            }
        }

        [Browsable(false), DefaultValue((string) null)]
        public object Value
        {
            get => 
                null;
            set
            {
            }
        }
    }
}

