// Assembly Accessibility, Version 2.0.0.0

[assembly: System.Runtime.InteropServices.ImportedFromTypeLib("Accessibility")]
[assembly: System.Reflection.AssemblyDefaultAlias("Accessibility.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.TypeLibVersion(1, 1)]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.5483")]
[assembly: System.Reflection.AssemblyDescription("Accessibility.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Resources.SatelliteContractVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.50727.5483")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.InteropServices.Guid("1ea4dbf0-3c3b-11cf-810c-00aa00389b71")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyTitle("Accessibility.dll")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\FinalPublicKey.snk")]

