// Assembly System.ServiceProcess, Version 2.0.0.0

[assembly: System.Reflection.AssemblyTitle("System.ServiceProcess.dll")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyDefaultAlias("System.ServiceProcess.dll")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyDescription("System.ServiceProcess.dll")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\FinalPublicKey.snk")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Resources.SatelliteContractVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.50727.5483")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.5483")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

