// Assembly System.DirectoryServices.Protocols, Version 2.0.0.0

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.50727.5492")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.5492")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\Tools\devdiv\FinalPublicKey.snk")]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Resources.SatelliteContractVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("Microsoft\x00ae .NET Framework")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.DirectoryServices.Protocols.dll")]
[assembly: System.Reflection.AssemblyTitle("System.DirectoryServices.Protocols.dll")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyDescription("System.DirectoryServices.Protocols.dll")]
[assembly: System.Net.NetworkInformation.NetworkInformationPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Unrestricted=true)]
[assembly: System.Security.Permissions.EnvironmentPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Unrestricted=true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, UnmanagedCode=true)]
[assembly: System.Net.WebPermission(System.Security.Permissions.SecurityAction.RequestMinimum, Unrestricted=true)]

